# Default values for modeldb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  modeldbBackendProxyImage:  vertaaiofficial/modeldb-proxy:latest
  modeldbBackendImage: vertaaiofficial/modeldb-backend:latest
  modeldbDatabaseImage: postgres
  modeldbFrontendImage: vertaaiofficial/modeldb-frontend:latest
service:
  modeldbFrontendService: LoadBalancer
  modeldbBackendService: ClusterIP
modeldbPostgresPvcSize: 20Gi
modeldbArtifactStorePvcSize: 1Gi
